server:
  port: 9000
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: chenyonghao1022
    url: jdbc:mysql://localhost:3306/16ban?useUnicode=true&characterEncoding=utf8&autoReconnect=true&useSSL=false&serverTimezone=UTC

mybatis:
  type-aliases-package: cn.edu.guet.insurance.bean
  mapper-locations: classpath:mapper/*Mapper.xml

#showSql
logging:
  level:
    cn.edu.guet.insurance.mapper: DEBUG
